<a href="https://colab.research.google.com/github/ElnazDi/colab/blob/master/Introduction_to_ML_Categorical_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# categorical variable : with three approaches 



1.    **Drop Categorical Variables:**

simply remove them from the dataset. This approach will only work well if the columns did not contain useful information.

2.  **Label Encoding :** Ordinal variables 

"Never" (0) < "Rarely" (1) < "Most days" (2) < "Every day" (3)

For tree-based models (like decision trees and random forests), you can expect label encoding to work well with ordinal variables.

3.   **One  Hot Encoding:**  Nominal variables 

does not perform well if the categorical variable takes on a large number of values

In [3]:
from google.colab import files
uploeaded_Seen = files.upload()
uploaded_Unseen = files.upload()

Saving test.csv to test (2).csv

Saving train.csv to train.csv

In [96]:
import pandas as pd

mel_seen_data = pd.read_csv('train.csv', index_col='Id')
mel_seen_data.head()

    MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
Id                                    ...
1           60       RL         65.0  ...        WD        Normal    208500
2           20       RL         80.0  ...        WD        Normal    181500
3           60       RL         68.0  ...        WD        Normal    223500
4           70       RL         60.0  ...        WD       Abnorml    140000
5           60       RL         84.0  ...        WD        Normal    250000

[5 rows x 80 columns]

In [97]:

mel_unseen_data = pd.read_csv('test.csv', index_col='Id')
mel_unseen_data.head()

      MSSubClass MSZoning  LotFrontage  ...  YrSold SaleType SaleCondition
Id                                      ...
1461          20       RH         80.0  ...    2010       WD        Normal
1462          20       RL         81.0  ...    2010       WD        Normal
1463          60       RL         74.0  ...    2010       WD        Normal
1464          60       RL         78.0  ...    2010       WD        Normal
1465         120       RL         43.0  ...    2010       WD        Normal

[5 rows x 79 columns]

In [98]:
mel_seen_data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [99]:
# We want to seprate X(predictores or features) and Y(target), As we can see there are NaN values in dataset
# Maybe there are also in SalePrice column so before seprating these two
# We drop them with dropna() in whole mel_seen_data dataset

mel_seen_data.dropna(axis=0, subset=['SalePrice'], inplace= True)
y = mel_seen_data.SalePrice
print(y.head())

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [0]:
mel_seen_data.drop(['SalePrice'],axis=1, inplace=True)

In [0]:
# To keep things simple, we'll drop columns with missing values ---> from past lesson:simple way
# 1. finding columns with missing values

cols_with_missing = [col for col in mel_seen_data.columns if mel_seen_data[col].isnull().any()]

# 2. Remove these missing values from both seen and unseen data

mel_seen_data.drop(cols_with_missing, axis=1, inplace= True)
mel_unseen_data.drop(cols_with_missing, axis=1, inplace=True)

In [0]:
# Seperate X_train, X_val, y_train, y_val from seen_data

from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(mel_seen_data, y,
                                                      train_size=0.8, test_size=0.2,
                                                      random_state=0)

In [103]:
X_train.head()

     MSSubClass MSZoning  LotArea Street  ... MoSold YrSold SaleType SaleCondition
Id                                        ...
619          20       RL    11694   Pave  ...      7   2007      New       Partial
871          20       RL     6600   Pave  ...      8   2009       WD        Normal
93           30       RL    13360   Pave  ...      8   2009       WD        Normal
818          20       RL    13265   Pave  ...      7   2008       WD        Normal
303          20       RL    13704   Pave  ...      1   2006       WD        Normal

[5 rows x 60 columns]

In [104]:
X_train.columns

Index(['MSSubClass', 'MSZoning', 'LotArea', 'Street', 'LotShape',
       'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood',
       'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'GarageCars', 'GarageArea', 'PavedDrive',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

In [0]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

def get_score(X_train, X_valid, y_train, y_valid):
  my_model = RandomForestRegressor(n_estimators=100, random_state=0)
  my_model.fit(X_train, y_train)
  prediction= my_model.predict(X_valid)
  return mean_absolute_error(y_valid, prediction)

As we can seen in dataset we have both numerical and categorical variables.  We'll need to encode the categorical data before training a model.

# Step 1: Drop columns with categorical data

In [106]:
# Only we need to exclude columns with object dtypes

without_obj_X_train = X_train.select_dtypes(exclude=['object'])
without_obj_X_valid = X_valid.select_dtypes(exclude=['object'])


#Get score for this approach

mae=get_score(without_obj_X_train , without_obj_X_valid, y_train, y_valid)
print("Mean Absolute Error for Approch One:")
print(mae)

Mean Absolute Error for Approch One:
17837.82570776256

# Step 2: Label encoding

In [107]:
X_train.Condition2   #Just as a example we look through one columns

Id
619     Norm
871     Norm
93      Norm
818     Norm
303     Norm
1455    Norm
41      Norm
960     Norm
76      Norm
1390    Norm
1255    Norm
690     Norm
649     Norm
248     Norm
1309    Norm
1165    Norm
709     Norm
187     Norm
157     Norm
915     Norm
9       Norm
391     Norm
1334    Norm
1442    Norm
620     Norm
772     Norm
466     Norm
1249    Norm
432     Norm
1289    Norm
        ...
1436    Norm
1202    Norm
100     Norm
851     Norm
449     Norm
756     Norm
977     Norm
116     Norm
778     Norm
73      Norm
846     Norm
538     Norm
850     Norm
175     Norm
88      Norm
552     Norm
706     Norm
315     Norm
1421    Norm
601     Norm
1095    Norm
600     Norm
278     Norm
1034    Norm
1384    Norm
764     Norm
836     Norm
1217    Norm
560     Norm
685     Norm
Name: Condition2, Length: 1168, dtype: object

In [108]:
# We want to investigate Column(Condition2) in both X_train and X_valid
# As we can see Norm in repeating to much here and we can not see any others
# So we want to see if are there any other values like Norm there? 
# we should use unique() to get their names once.

uni_names=X_train['Condition2'].unique()
print(uni_names)

uni_names=X_valid['Condition2'].unique()
print(uni_names)

['Norm' 'PosA' 'Feedr' 'PosN' 'Artery' 'RRAe']
['Norm' 'RRAn' 'RRNn' 'Artery' 'Feedr' 'PosN']

**We can see lables in X_train and X_valid are not same, This will cause error**

Fitting a label encoder to a column in the training data creates a corresponding integer-valued label for each unique value that appears in the training data. In the case that the validation data contains values that don't also appear in the training data, the encoder will throw an error, because these values won't have an integer assigned to them. Notice that the 'Condition2' column in the validation data contains the values 'RRAn' and 'RRNn', but these don't appear in the training data -- thus, if we try to use a label encoder with scikit-learn, the code will throw an error.






This is a common problem that you'll encounter with real-world data, and there are many approaches to fixing this issue. For instance, you can write a custom label encoder to deal with new categories. The simplest approach, however, is to drop the problematic categorical columns.

In [117]:
# We want to seperate Good lables (sames) from Bad lables (differents) in both test and train

# Select all columns with categorical data
#Select all columns with Good lables (same in both train and val)
# Bad_lables = All - Good

all_categorical_cols = [col for col in X_train.columns if X_train[col].dtype == 'object']
good_lable_cols = [col for col in all_categorical_cols  if set(X_train[col]) ==  set(X_valid[col])]
bad_lable_cols = list(set(all_categorical_cols) - set(good_lable_cols))

print("Good Lables are: \n", good_lable_cols)
print("\nBad Lables are: \n", bad_lable_cols)

Good Lables are:
 ['MSZoning', 'Street', 'LotShape', 'LandContour', 'LotConfig', 'BldgType', 'HouseStyle', 'ExterQual', 'CentralAir', 'KitchenQual', 'PavedDrive', 'SaleCondition']

Bad Lables are:
 ['ExterCond', 'RoofStyle', 'SaleType', 'Foundation', 'HeatingQC', 'LandSlope', 'RoofMatl', 'Functional', 'Exterior2nd', 'Utilities', 'Exterior1st', 'Heating', 'Condition2', 'Condition1', 'Neighborhood']

In [0]:
# Now we need to drop these bad lables from dataset

from sklearn.preprocessing import LabelEncoder

# Drop categorical columns that will not be encoded
X_train_GL = X_train.drop(bad_lable_cols, axis=1)
X_valid_GL = X_valid.drop(bad_lable_cols, axis=1)

lable_encoder = LabelEncoder()
for col in set(good_lable_cols):
  X_train_GL[col] = lable_encoder.fit_transform(X_train[col])
  X_valid_GL[col] = lable_encoder.transform(X_valid[col])

In [119]:
# Get score for this approach

print("Mean Absolute Error in Second Approach: \n")

mae = get_score(X_train_GL, X_valid_GL, y_train, y_valid)
print(mae)

Mean Absolute Error in Second Approach:

17575.291883561644

# Step 3: Investigating cardinality

** **
**Cardinality:**  This step 3 does not work well as is not important for the rest of the code

We refer to the number of unique entries of a categorical variable as the **cardinality** of that categorical variable.

In [120]:
# Get number of unique entries in each column with categorical data
object_nunique = list(map(lambda col: X_train[col].nunique(), all_categorical_cols))
d = dict(zip(all_categorical_cols, all_categorical_cols))

# Print number of unique entries by column, in ascending order
sorted(d.items(), key=lambda x: x[1])

[('BldgType', 'BldgType'),
 ('CentralAir', 'CentralAir'),
 ('Condition1', 'Condition1'),
 ('Condition2', 'Condition2'),
 ('ExterCond', 'ExterCond'),
 ('ExterQual', 'ExterQual'),
 ('Exterior1st', 'Exterior1st'),
 ('Exterior2nd', 'Exterior2nd'),
 ('Foundation', 'Foundation'),
 ('Functional', 'Functional'),
 ('Heating', 'Heating'),
 ('HeatingQC', 'HeatingQC'),
 ('HouseStyle', 'HouseStyle'),
 ('KitchenQual', 'KitchenQual'),
 ('LandContour', 'LandContour'),
 ('LandSlope', 'LandSlope'),
 ('LotConfig', 'LotConfig'),
 ('LotShape', 'LotShape'),
 ('MSZoning', 'MSZoning'),
 ('Neighborhood', 'Neighborhood'),
 ('PavedDrive', 'PavedDrive'),
 ('RoofMatl', 'RoofMatl'),
 ('RoofStyle', 'RoofStyle'),
 ('SaleCondition', 'SaleCondition'),
 ('SaleType', 'SaleType'),
 ('Street', 'Street'),
 ('Utilities', 'Utilities')]

In [0]:
# have cardinality greater than 10?
high_cardinality_numcols = 3

# Fill in the line below: How many columns are needed to one-hot encode the 
# 'Neighborhood' variable in the training data?
num_cols_neighborhood = 25

For large datasets with many rows, one-hot encoding can greatly expand the size of the dataset.  For this reason, we typically will only one-hot encode columns with relatively low cardinality.  Then, high cardinality columns can either be dropped from the dataset, or we can use label encoding.

As an example, consider a dataset with 10,000 rows, and containing one categorical column with 100 unique entries.  
- If this column is replaced with the corresponding one-hot encoding, how many entries are added to the dataset?  
- If we instead replace the column with the label encoding, how many entries are added?  

Use your answers to fill in the lines below.

In [0]:
# Fill in the line below: How many entries are added to the dataset by 
# replacing the column with a one-hot encoding?
OH_entries_added = 1e4*100 - 1e4

# Fill in the line below: How many entries are added to the dataset by
# replacing the column with a label encoding?
label_entries_added = 0

# Step 4: One-hot encoding

In this step, you'll experiment with one-hot encoding.  But, instead of encoding all of the categorical variables in the dataset, you'll only create a one-hot encoding for columns with cardinality less than 10.

Run the code cell below without changes to set `low_cardinality_cols` to a Python list containing the columns that will be one-hot encoded.  Likewise, `high_cardinality_cols` contains a list of categorical columns that will be dropped from the dataset.

In [124]:
# Columns that will be one-hot encoded
low_cardinality_cols = [col for col in all_categorical_cols if X_train[col].nunique() < 10]

# Columns that will be dropped from the dataset
high_cardinality_cols = list(set(all_categorical_cols)-set(low_cardinality_cols))

print('Categorical columns that will be one-hot encoded:', low_cardinality_cols)
print('\nCategorical columns that will be dropped from the dataset:', high_cardinality_cols)

Categorical columns that will be one-hot encoded: ['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'ExterQual', 'ExterCond', 'Foundation', 'Heating', 'HeatingQC', 'CentralAir', 'KitchenQual', 'Functional', 'PavedDrive', 'SaleType', 'SaleCondition']

Categorical columns that will be dropped from the dataset: ['Exterior1st', 'Exterior2nd', 'Neighborhood']

We use the OneHotEncoder class from scikit-learn to get one-hot encodings. There are a number of parameters that can be used to customize its behavior.

 **handle_unknown='ignore'**

to avoid errors when the validation data contains classes that aren't represented in the training data, and


***setting sparse=False ***

ensures that the encoded columns are returned as a numpy array (instead of a sparse matrix).

In [0]:
from sklearn.preprocessing import OneHotEncoder

# Apply one-hot encoder to each column with categorical data
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(X_train[low_cardinality_cols]))
OH_cols_valid = pd.DataFrame(OH_encoder.transform(X_valid[low_cardinality_cols]))

# One-hot encoding removed index; put it back
OH_cols_train.index = X_train.index
OH_cols_valid.index = X_valid.index

# Remove categorical columns (will replace with one-hot encoding)
num_X_train = X_train.drop(all_categorical_cols, axis=1)
num_X_valid = X_valid.drop(all_categorical_cols, axis=1)

# Add one-hot encoded columns to numerical features
OH_X_train = pd.concat([num_X_train, OH_cols_train], axis=1)
OH_X_valid = pd.concat([num_X_valid, OH_cols_valid], axis=1)

In [129]:
print("MAE from Approach 3 (One-Hot Encoding):") 
print(get_score(OH_X_train, OH_X_valid, y_train, y_valid))

MAE from Approach 3 (One-Hot Encoding):
17525.345719178084